- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - keys.yaml
  vars:
    env: test
  tasks:
    - name: created a VPC with default tenancy
      ec2_vpc_net:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: present
        name: "{{ env }}-VPC"
        cidr_block: 10.0.0.0/16
        tags:
          env: "{{ env }}"
        tenancy: default
    - name: Get VPC facts
      ec2_vpc_net_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
      register: vpc_facts
    - debug:
        var: vpc_facts.vpcs[1].vpc_id
    - name: create public subnet-1 in VPC
      ec2_vpc_subnet:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: present
        vpc_id: "{{ vpc_facts.vpcs[1].vpc_id }}"
        cidr: 10.0.0.0/24
        az: "{{ AWS_REGION }}a"
        map_public: yes
        wait: yes
        tags:
          Name: "{{ env }}-public-1"
    - name: create public subnet-2 in VPC
      ec2_vpc_subnet:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: present
        vpc_id: "{{ vpc_facts.vpcs[1].vpc_id }}"
        cidr: 10.0.1.0/24
        az: "{{ AWS_REGION }}b"
        map_public: yes
        wait: yes
        tags:
          Name: "{{ env }}-public-2"
    - name: create private subnet-1 in VPC
      ec2_vpc_subnet:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: present
        vpc_id: "{{ vpc_facts.vpcs[1].vpc_id }}"
        cidr: 10.0.2.0/24
        az: "{{ AWS_REGION }}a"
        map_public: no
        wait: yes
        tags:
          Name: "{{ env }}-private-1"
    - name: create private subnet-2 in VPC
      ec2_vpc_subnet:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: present
        vpc_id: "{{ vpc_facts.vpcs[1].vpc_id }}"
        cidr: 10.0.3.0/24
        az: "{{ AWS_REGION }}b"
        map_public: no
        wait: yes
        tags:
          Name: "{{ env }}-private-2"
